import type { Authentication } from "./types";

import type {
  GetExchangeInfoParams,
  GetOrderBookParams,
  GetRecentTradesParams,
  GetHistoricalTradesParams,
  GetAggregateTradesParams,
  GetKlinesParams,
  GetUIKlinesParams,
  GetCurrentAveragePriceParams,
  GetPriceChangeStatsParams,
  GetTradingDayTickerParams,
  GetSymbolPriceTickerParams,
  GetSymbolOrderBookTickerParams,
  GetRollingWindowPriceChangeStatsParams,
} from "./endpoints/market";

import type {
  CreateNewTestOrderParams,
  CreateNewOrderParams,
  CancelOrderParams,
  CancelAllOpenOrdersParams,
  GetOrderParams,
  CancelReplaceOrderParams,
  GetCurrentOpenOrdersParams,
  GetAllOrdersParams,
  CreateNewOcoOrderParams,
  CreateNewOcoOrderListParams,
  CreateNewOtoOrderListParams,
  CreateNewOtocoOrderListParams,
  CancelOrderListParams,
  GetOrderListParams,
  GetAllOrderListParams,
  GetOpenOrderListParams,
  CreateNewOrderSorParams,
  TestNewOrderSorParams,
  GetAccountInformationParams,
  GetAccountTradeListParams,
  GetUnfilledOrderCountParams,
  GetPreventedMatchesParams,
  GetAllocationsParams,
  GetComissionRatesParams,
} from "./endpoints/spot";

import type {
  MarginBorrowRepayParams,
  MarginBorrowRepayRecordsParams,
  AllMarginAssetsParams,
  AllCrossMarginPairsParams,
  MarginPriceIndexParams,
  CreateMarginOrderParams,
  CancelMarginOrderParams,
  CancelAllMarginOrdersParams,
  AdjustCrossMarginLeverageParams,
  MarginTransferHistoryParams,
  GetMarginInterestHistoryParams,
  GetMarginForceLiquidationRecordParams,
  GetCrossMarginAccountDetailsParams,
  GetMarginOrderParams,
  GetMarginOpenOrdersParams,
  GetMarginAllOrdersParams,
  CreateMarginOcoOrderParams,
  CancelMarginOcoOrderParams,
  GetMarginOcoOrderParams,
  GetMarginAllOcoOrdersParams,
  GetMarginOpenOcoOrdersParams,
  GetMarginAccountTradeListParams,
  GetMarginMaxBorrowableParams,
  GetMarginMaxTransferableParams,
  GetMarginAccountSummaryParams,
  GetIsolatedMarginAccountInfoParams,
  DisableIsolatedMarginAccountParams,
  EnableIsolatedMarginAccountParams,
  GetIsolatedMarginAccountLimitParams,
  GetAllIsolatedMarginSymbolParams,
  ToggleBnbBurnStatusParams,
  GetBnbBurnStatusParams,
  GetMarginInterestRateHistoryParams,
  GetCrossMarginFeeDataParams,
  GetIsolatedMarginFeeDataParams,
  GetIsolatedMarginTierDataParams,
  GetCurrentMarginOrderCountParams,
  GetSmallLiabilityExchangeCoinListParams,
  GetNextHourlyInterestRateParams,
  GetMarginCapitalFlowParams,
  GetMarginDelistScheduleParams,
  GetMarginAvailableInventoryParams,
  LiquidateMarginSymbolManuallyParams,
} from "./endpoints/margin";

import type {
  GetAllCoinsInfoParams,
  GetAccountSnapshotParams,
  DisableFastWithdrawSwitchParams,
  EnableFastWithdrawSwitchParams,
  WithdrawFundParams,
  GetDepositHistoryParams,
  GetWithdrawHistoryParams,
  GetDepositAddressParams,
  GetAccountStatusParams,
  GetAccountApiTradingStatusParams,
  GetDustLogParams,
  GetBnbConvertableAssetsParams,
  DustTransferParams,
  GetAssetDividendRecordParams,
  GetAssetDetailParams,
  GetTradeFeeParams,
  UserUniversalTransferParams,
  GetUserUniversalTransferHistoryParams,
  GetFundingWalletParams,
  GetUserAssetParams,
  ConvertBusdParams,
  GetConvertBusdHistoryParams,
  GetCloudMiningTransactionHistoryParams,
  GetApiKeyPermissionsParams,
  SwitchStableCoinConversionParams,
  ApplyOneClickArrivalDepositParams,
  GetDepositAddressListParams,
  GetUserWalletBalanceParams,
  GetMasterAccountUserDelegationHistoryParams,
  GetSpotSymbolsDelistScheduleParams,
  GetAccountInfoParams,
} from "./endpoints/wallet";

import { market } from "./endpoints/market";
import { spot } from "./endpoints/spot";
import { margin } from "./endpoints/margin";
import { wallet } from "./endpoints/wallet";

const binance = {
  market,
  spot,
  margin,
  wallet,
};

// Comment to trigger action
export default binance;

export type { Authentication };

export type {
  GetExchangeInfoParams,
  GetOrderBookParams,
  GetRecentTradesParams,
  GetHistoricalTradesParams,
  GetAggregateTradesParams,
  GetKlinesParams,
  GetUIKlinesParams,
  GetCurrentAveragePriceParams,
  GetPriceChangeStatsParams,
  GetTradingDayTickerParams,
  GetSymbolPriceTickerParams,
  GetSymbolOrderBookTickerParams,
  GetRollingWindowPriceChangeStatsParams,
};

export type {
  CreateNewTestOrderParams,
  CreateNewOrderParams,
  CancelOrderParams,
  CancelAllOpenOrdersParams,
  GetOrderParams,
  CancelReplaceOrderParams,
  GetCurrentOpenOrdersParams,
  GetAllOrdersParams,
  CreateNewOcoOrderParams,
  CreateNewOcoOrderListParams,
  CreateNewOtoOrderListParams,
  CreateNewOtocoOrderListParams,
  CancelOrderListParams,
  GetOrderListParams,
  GetAllOrderListParams,
  GetOpenOrderListParams,
  CreateNewOrderSorParams,
  TestNewOrderSorParams,
  GetAccountInformationParams,
  GetAccountTradeListParams,
  GetUnfilledOrderCountParams,
  GetPreventedMatchesParams,
  GetAllocationsParams,
  GetComissionRatesParams,
};

export type {
  MarginBorrowRepayParams,
  MarginBorrowRepayRecordsParams,
  AllMarginAssetsParams,
  AllCrossMarginPairsParams,
  MarginPriceIndexParams,
  CreateMarginOrderParams,
  CancelMarginOrderParams,
  CancelAllMarginOrdersParams,
  AdjustCrossMarginLeverageParams,
  MarginTransferHistoryParams,
  GetMarginInterestHistoryParams,
  GetMarginForceLiquidationRecordParams,
  GetCrossMarginAccountDetailsParams,
  GetMarginOrderParams,
  GetMarginOpenOrdersParams,
  GetMarginAllOrdersParams,
  CreateMarginOcoOrderParams,
  CancelMarginOcoOrderParams,
  GetMarginOcoOrderParams,
  GetMarginAllOcoOrdersParams,
  GetMarginOpenOcoOrdersParams,
  GetMarginAccountTradeListParams,
  GetMarginMaxBorrowableParams,
  GetMarginMaxTransferableParams,
  GetMarginAccountSummaryParams,
  GetIsolatedMarginAccountInfoParams,
  DisableIsolatedMarginAccountParams,
  EnableIsolatedMarginAccountParams,
  GetIsolatedMarginAccountLimitParams,
  GetAllIsolatedMarginSymbolParams,
  ToggleBnbBurnStatusParams,
  GetBnbBurnStatusParams,
  GetMarginInterestRateHistoryParams,
  GetCrossMarginFeeDataParams,
  GetIsolatedMarginFeeDataParams,
  GetIsolatedMarginTierDataParams,
  GetCurrentMarginOrderCountParams,
  GetSmallLiabilityExchangeCoinListParams,
  GetNextHourlyInterestRateParams,
  GetMarginCapitalFlowParams,
  GetMarginDelistScheduleParams,
  GetMarginAvailableInventoryParams,
  LiquidateMarginSymbolManuallyParams,
};

export type {
  GetAllCoinsInfoParams,
  GetAccountSnapshotParams,
  DisableFastWithdrawSwitchParams,
  EnableFastWithdrawSwitchParams,
  WithdrawFundParams,
  GetDepositHistoryParams,
  GetWithdrawHistoryParams,
  GetDepositAddressParams,
  GetAccountStatusParams,
  GetAccountApiTradingStatusParams,
  GetDustLogParams,
  GetBnbConvertableAssetsParams,
  DustTransferParams,
  GetAssetDividendRecordParams,
  GetAssetDetailParams,
  GetTradeFeeParams,
  UserUniversalTransferParams,
  GetUserUniversalTransferHistoryParams,
  GetFundingWalletParams,
  GetUserAssetParams,
  ConvertBusdParams,
  GetConvertBusdHistoryParams,
  GetCloudMiningTransactionHistoryParams,
  GetApiKeyPermissionsParams,
  SwitchStableCoinConversionParams,
  ApplyOneClickArrivalDepositParams,
  GetDepositAddressListParams,
  GetUserWalletBalanceParams,
  GetMasterAccountUserDelegationHistoryParams,
  GetSpotSymbolsDelistScheduleParams,
  GetAccountInfoParams,
};
