import type { Authentication } from "./types";

import type {
  ExchangeInfoParams,
  OrderBookParams,
  RecentTradesParams,
  HistoricalTradesParams,
  AggregateTradesParams,
  KlineParams,
  UIKlinesParams,
  CurrentAveragePriceParams,
  PriceChangeStatsParams,
  TradingDayTickerParamsSymbol,
  TradingDayTickerParamsSymbols,
  SymbolPriceTickerParams,
  SymbolOrderBookTickerParams,
  RollingWindowPriceChangeStatsParamsSymbol,
  RollingWindowPriceChangeStatsParamsSymbols,
} from "./endpoints/market";

import type {
  TestNewOrderParams,
  NewOrderParams,
  CancelOrderParams,
  CancelAllOpenOrdersParams,
  QueryOrderParams,
  CancelReplaceOrderParams,
  CurrentOpenOrdersParams,
  AllOrdersParams,
  NewOcoOrderParams,
  NewOcoOrderListParams,
  NewOtoOrderListParams,
  NewOtocoOrderListParams,
  CancelOrderListParams,
  QueryOrderListParams,
  QueryAllOrderListParams,
  QueryOpenOrderListParams,
  NewOrderSorParams,
  TestNewOrderSorParams,
  AccountInformationParams,
  AccountTradeListParams,
  QueryUnfilledOrderCountParams,
  QueryPreventedMatchesParams,
  QueryAllocationsParams,
  QueryComissionRatesParams,
} from "./endpoints/spot";

import type {
  MarginBorrowRepayParams,
  MarginBorrowRepayRecordsParams,
  AllMarginAssetsParams,
  AllCrossMarginPairsParams,
  MarginPriceIndexParams,
  CreateMarginOrderParams,
  CancelMarginOrderParams,
  CancelAllMarginOrdersParams,
  AdjustCrossMarginLeverageParams,
  MarginTransferHistoryParams,
  GetMarginInterestHistoryParams,
  GetMarginForceLiquidationRecordParams,
  GetCrossMarginAccountDetailsParams,
  GetMarginOrderParams,
  GetMarginOpenOrdersParams,
  GetMarginAllOrdersParams,
  CreateMarginOcoOrderParams,
  CancelMarginOcoOrderParams,
  GetMarginOcoOrderParams,
  GetMarginAllOcoOrdersParams,
  GetMarginOpenOcoOrdersParams,
  GetMarginAccountTradeListParams,
  GetMarginMaxBorrowableParams,
  GetMarginMaxTransferableParams,
  GetMarginAccountSummaryParams,
  GetIsolatedMarginAccountInfoParams,
  DisableIsolatedMarginAccountParams,
  EnableIsolatedMarginAccountParams,
  GetIsolatedMarginAccountLimitParams,
  GetAllIsolatedMarginSymbolParams,
  ToggleBnbBurnStatusParams,
  GetBnbBurnStatusParams,
  GetMarginInterestRateHistoryParams,
  GetCrossMarginFeeDataParams,
  GetIsolatedMarginFeeDataParams,
  GetIsolatedMarginTierDataParams,
  GetCurrentMarginOrderCountParams,
  GetSmallLiabilityExchangeCoinListParams,
  GetNextHourlyInterestRateParams,
  GetMarginCapitalFlowParams,
  GetMarginDelistScheduleParams,
  GetMarginAvailableInventoryParams,
  LiquidateMarginSymbolManuallyParams,
} from "./endpoints/margin";

import type {
  GetAllCoinsInfoParams,
  GetAccountSnapshotParams,
  DisableFastWithdrawSwitchParams,
  EnableFastWithdrawSwitchParams,
  WithdrawFundParams,
  GetDepositHistoryParams,
  GetWithdrawHistoryParams,
  GetDepositAddressParams,
  GetAccountStatusParams,
  GetAccountApiTradingStatusParams,
  GetDustLogParams,
  GetBnbConvertableAssetsParams,
  DustTransferParams,
  GetAssetDividendRecordParams,
  GetAssetDetailParams,
  GetTradeFeeParams,
  UserUniversalTransferParams,
  GetUserUniversalTransferHistoryParams,
  GetFundingWalletParams,
  GetUserAssetParams,
  ConvertBusdParams,
  GetConvertBusdHistoryParams,
  GetCloudMiningTransactionHistoryParams,
  GetApiKeyPermissionsParams,
  SwitchStableCoinConversionParams,
  ApplyOneClickArrivalDepositParams,
  GetDepositAddressListParams,
  GetUserWalletBalanceParams,
  GetMasterAccountUserDelegationHistoryParams,
  GetSpotSymbolsDelistScheduleParams,
  GetAccountInfoParams,
} from "./endpoints/wallet";

import { market } from "./endpoints/market";
import { spot } from "./endpoints/spot";
import { margin } from "./endpoints/margin";
import { wallet } from "./endpoints/wallet";

const binance = {
  market,
  spot,
  margin,
  wallet,
};

// Comment to trigger action
export default binance;
